### PR TITLE
Update BitIntegers.jl dep

### PR DESCRIPTION
**Pull request by tamasgal**
There is now 0.3.0 which should be fine.

### CODE REVIEW

**Comment by tamasgal** [comment]
@Moelf not urgent at all, just wanted to updated the deps since BitIntegers 0.3.0 is out (I have a small dependency clash with one of our internal libs, but as said, no big worries right now).

Somehow the `isbits`-thingy is not working properly, see https://github.com/JuliaHEP/UnROOT.jl/actions/runs/5043464521/jobs/9045281206?pr=250 and below

```
RNTuple Tables.jl and Arrow integration : Error During Test at /home/runner/work/UnROOT.jl/UnROOT.jl/test/rntuple_tests.jl:174
  Got exception outside of a @test
  `write` is not supported on non-isbits arrays
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] write(s::IOStream, A::LazyTree with 13 branches:
  string, vector_int32, array_float, vector_vector_int32, vector_string...

```

**Comment by Moelf** [comment]
I assume because there's a breaking change? which is why they bumped to 0.3.0? I will look

**Comment by Moelf** [comment]
I think it might be Arrow.jl breaking

**Comment by Moelf** [comment]
https://github.com/apache/arrow-julia/commit/b2a832eae1071e0cee211b211039a74a838def11

ah.......... so 
```julia
(UnROOT) pkg> add Arrow@2.5.2
   Resolving package versions...
   Installed Arrow ─ v2.5.2
    Updating `~/Documents/github/dotFiles/homedir/.julia/dev/UnROOT/Project.toml`
  [69666777] ↑ Arrow v0.2.4 ⇒ v2.5.2
⌅ [c3b6d118] ↓ BitIntegers v0.3.0 ⇒ v0.2.7
    Updating `~/Documents/github/dotFiles/homedir/.julia/dev/UnROOT/Manifest.toml`
  [69666777] ↑ Arrow v0.2.4 ⇒ v2.5.2
  [31f734f8] + ArrowTypes v2.1.0
⌅ [c3b6d118] ↓ BitIntegers v0.3.0 ⇒ v0.2.7
  [324d7699] - CategoricalArrays v0.8.3
  [e2ba6199] + ExprTools v0.1.9
  [682c06a0] - JSON v0.21.4

**Comment by tamasgal** [comment]
Oh ok. These dependencies are slowly getting more and more annoying 🙈

**Comment by tamasgal** [comment]
There is a clash with `SSL_jll` and the fallback version of `HDF5_jll` is not compiled for M1 ;D

**Comment by tamasgal** [comment]
Ah, don't worry, that needs to be fixed upstream anyways!

**Review by Moelf — APPROVED** [review]

**Pull request merged**
