### PR TITLE
add promote_rule for Index64

### LINKED ISSUE #321: [RNTuple] OutOfMemoryError in show()
With a RNTuple file (RC2) and the master branch of UnROOT I am getting  `OutOfMemoryError`s when getting columns. The file to reproduce can be obtain with this shared link: https://cernbox.cern.ch/s/LekZWhLdulXucni

Here is the reproducer:
```Julia
julia> using UnROOT

julia> tfile = ROOTFile("/Users/mato/cernbox/Data/events_000189367-rntuple-rc2.root")
ROOTFile with 2 entries and 0 streamers.
/Users/mato/cernbox/Data/events_000189367-rntuple-rc2.root
├─ events (ROOT::Experimental::RNTuple)
└─ podio_metadata (ROOT::Experimental::RNTuple)


julia> events = LazyTree(tfile,"events");
julia> evt = events[1];

julia> evt = events[1];

julia> evt.ReconstructedParticles
83-element StructArray(view(::Vector{Int32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), StructArray(view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053)), StructArray(view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053)), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(reinterpret(StaticArraysCore.SVector{10, Float32}, ::Vector{Float32}), 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053), view(::Vector{UInt32}, 0x0000000000000001:0x0000000000000053)) with eltype @NamedTuple{type::Int32, energy::Float32, momentum::@NamedTuple{x::Float32, y::Float32, z::Float32}, referencePoint::@NamedTuple{x::Float32, y::Float32, z::Float32}, charge::Float32, mass::Float32, goodnessOfPID::Float32, covMatrix::StaticArraysCore.SVector{10, Float32}, clusters_begin::UInt32, clusters_end::UInt32, tracks_begin::UInt32, tracks_end::UInt32, particles_begin::UInt32, particles_end::UInt32, particleIDs_begin::UInt32, particleIDs_end::UInt32}:
 (type = 0, energy = 0.20443569, momentum = (x = -0.12986459, y = 0.027864397, z = -0.06835884), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000000, tracks_end = 0x00000001, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000000, particleIDs_end = 0x00000001)
 (type = 0, energy = 0.19994973, momentum = (x = -0.1047018, y = 0.038945146, z = -0.08955956), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000001, tracks_end = 0x00000002, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000001, particleIDs_end = 0x00000002)
 (type = 0, energy = 0.29208112, momentum = (x = -0.17289947, y = 0.18287736, z = -0.04993235), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000002, tracks_end = 0x00000003, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000002, particleIDs_end = 0x00000003)
 (type = 0, energy = 0.83355635, momentum = (x = -0.091049485, y = -0.30193385, z = -0.7588692), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000003, tracks_end = 0x00000004, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000003, particleIDs_end = 0x00000004)
 (type = 0, energy = 0.7275338, momentum = (x = 0.21555881, y = -0.22806452, z = -0.64136314), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000004, tracks_end = 0x00000005, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000004, particleIDs_end = 0x00000005)
 (type = 0, energy = 0.37446955, momentum = (x = -0.22464286, y = -0.20334218, z = -0.17010352), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000005, tracks_end = 0x00000006, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000005, particleIDs_end = 0x00000006)
 (type = 0, energy = 4.5689936, momentum = (x = -1.5054878, y = -1.8047847, z = -3.915671), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000006, tracks_end = 0x00000007, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000006, particleIDs_end = 0x00000007)
 (type = 0, energy = 1.9894301, momentum = (x = -0.8030898, y = -0.9157472, z = -1.5667821), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000007, tracks_end = 0x00000008, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000007, particleIDs_end = 0x00000008)
 (type = 0, energy = 2.2148736, momentum = (x = -0.59422237, y = -1.2480376, z = -1.4541721), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000008, tracks_end = 0x00000009, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000008, particleIDs_end = 0x00000009)
 (type = 0, energy = 0.915481, momentum = (x = -0.7203761, y = -0.0105718, z = -0.54733187), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x00000009, tracks_end = 0x0000000a, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x00000009, particleIDs_end = 0x0000000a)
 (type = 0, energy = 2.3581483, momentum = (x = -1.033541, y = -1.4063002, z = -1.5797141), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x0000000a, tracks_end = 0x0000000b, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x0000000a, particleIDs_end = 0x0000000b)
 (type = 0, energy = 0.81072587, momentum = (x = -0.5913454, y = -0.3650383, z = -0.39351526), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x0000000b, tracks_end = 0x0000000c, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x0000000b, particleIDs_end = 0x0000000c)
 (type = 0, energy = 11.4611635, momentum = (x = -0.27757546, y = 10.611775, z = -4.3187914), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x0000000c, tracks_end = 0x0000000d, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x0000000c, particleIDs_end = 0x0000000d)
 (type = 0, energy = 1.8676314, momentum = (x = 1.368267, y = -1.078922, z = -0.6575256), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = -1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x0000000d, tracks_end = 0x0000000e, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x0000000d, particleIDs_end = 0x0000000e)
 (type = 0, energy = 1.1010642, momentum = (x = 0.06854927, y = 1.0366745, z = -0.3368523), referencePoint = (x = 0.0, y = 0.0, z = 0.0), charge = 1.0, mass = 0.13957039, goodnessOfPID = 0.0, covMatrix = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], clusters_begin = 0x00000000, clusters_end = 0x00000000, tracks_begin = 0x0000000e, tracks_end = 0x0000000f, particles_begin = 0x00000000, particles_end = 0x00000000, particleIDs_begin = 0x0000000e, particleIDs_end = 0x0000000f)
 Error showing value of type StructArrays.StructVector{@NamedTuple{type::Int32, energy::Float32, momentum::@NamedTuple{x::Float32, y::Float32, z::Float32}, referencePoint::@NamedTuple{x::Float32, y::Float32, z::Float32}, charge::Float32, mass::Float32, goodnessOfPID::Float32, covMatrix::StaticArraysCore.SVector{10, Float32}, clusters_begin::UInt32, clusters_end::UInt32, tracks_begin::UInt32, tracks_end::UInt32, particles_begin::UInt32, particles_end::UInt32, particleIDs_begin::UInt32, particleIDs_end::UInt32}, @NamedTuple{type::SubArray{Int32, 1, Vector{Int32}, Tuple{UnitRange{UnROOT.Index64}}, true}, energy::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, momentum::StructArrays.StructVector{@NamedTuple{x::Float32, y::Float32, z::Float32}, @NamedTuple{x::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, y::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, z::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}}, Int64}, referencePoint::StructArrays.StructVector{@NamedTuple{x::Float32, y::Float32, z::Float32}, @NamedTuple{x::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, y::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, z::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}}, Int64}, charge::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, mass::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, goodnessOfPID::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, covMatrix::SubArray{StaticArraysCore.SVector{10, Float32}, 1, Base.ReinterpretArray{StaticArraysCore.SVector{10, Float32}, 1, Float32, Vector{Float32}, false}, Tuple{UnitRange{UnROOT.Index64}}, true}, clusters_begin::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, clusters_end::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, tracks_begin::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, tracks_end::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, particles_begin::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, particles_end::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, particleIDs_begin::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}, particleIDs_end::SubArray{UInt32, 1, Vector{UInt32}, Tuple{UnitRange{UnROOT.Index64}}, true}}, Int64}:
ERROR: OutOfMemoryError()
Stacktrace:
  [1] _string_n
    @ ./strings/string.jl:90 [inlined]
  [2] repeat(s::String, r::UnROOT.Index64)
    @ Base ./strings/substring.jl:267
  [3] print_matrix_vdots(io::IOContext{Base.TTY}, vdots::String, A::Vector{Tuple{…}}, sep::String, M::Int64, m::Int64, pad_right::Bool)
    @ Base ./arrayshow.jl:138
  [4] _print_matrix(io::IOContext{…}, X::AbstractVecOrMat, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64, rowsA::UnitRange{…}, colsA::UnitRange{…})
    @ Base ./arrayshow.jl:240
  [5] print_matrix(io::IOContext{…}, X::StructArrays.StructVector{…}, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64)
    @ Base ./arrayshow.jl:171
  [6] 
    @ Base ./arrayshow.jl:171 [inlined]
  [7] print_array
    @ ./arrayshow.jl:358 [inlined]
  [8] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, X::StructArrays.StructVector{@NamedTuple{…}, @NamedTuple{…}, Int64})
    @ Base ./arrayshow.jl:399
  [9] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:273
 [10] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [11] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:259
 [12] display
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:278 [inlined]
 [13] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [14] #invokelatest#2
    @ ./essentials.jl:887 [inlined]
 [15] invokelatest
    @ ./essentials.jl:884 [inlined]
 [16] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:315
 [17] (::REPL.var"#57#58"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:284
 [18] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [19] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:282
 [20] (::REPL.var"#do_respond#80"{…})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:911
 [21] #invokelatest#2
    @ Base ./essentials.jl:887 [inlined]
 [22] invokelatest
    @ Base ./essentials.jl:884 [inlined]
 [23] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2656
 [24] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1312
 [25] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:386
Some type information was truncated. Use `show(err)` to see complete types.

julia> evt.ReconstructedParticles.momentum
83-element StructArray(view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053), view(::Vector{Float32}, 0x0000000000000001:0x0000000000000053)) with eltype @NamedTuple{x::Float32, y::Float32, z::Float32}:
 (x = -0.12986459, y = 0.027864397, z = -0.06835884)
 (x = -0.1047018, y = 0.038945146, z = -0.08955956)
 (x = -0.17289947, y = 0.18287736, z = -0.04993235)
 (x = -0.091049485, y = -0.30193385, z = -0.7588692)
 (x = 0.21555881, y = -0.22806452, z = -0.64136314)
 (x = -0.22464286, y = -0.20334218, z = -0.17010352)
 (x = -1.5054878, y = -1.8047847, z = -3.915671)
 (x = -0.8030898, y = -0.9157472, z = -1.5667821)
 (x = -0.59422237, y = -1.2480376, z = -1.4541721)
 (x = -0.7203761, y = -0.0105718, z = -0.54733187)
 (x = -1.033541, y = -1.4063002, z = -1.5797141)
 (x = -0.5913454, y = -0.3650383, z = -0.39351526)
 (x = -0.27757546, y = 10.611775, z = -4.3187914)
 (x = 1.368267, y = -1.078922, z = -0.6575256)
 (x = 0.06854927, y = 1.0366745, z = -0.3368523)
 Error showing value of type StructArrays.StructVector{@NamedTuple{x::Float32, y::Float32, z::Float32}, @NamedTuple{x::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, y::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}, z::SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{UnROOT.Index64}}, true}}, Int64}:
ERROR: OutOfMemoryError()
Stacktrace:
  [1] _string_n
    @ ./strings/string.jl:90 [inlined]
  [2] repeat(s::String, r::UnROOT.Index64)
    @ Base ./strings/substring.jl:267
  [3] print_matrix_vdots(io::IOContext{Base.TTY}, vdots::String, A::Vector{Tuple{…}}, sep::String, M::Int64, m::Int64, pad_right::Bool)
    @ Base ./arrayshow.jl:138
  [4] _print_matrix(io::IOContext{…}, X::AbstractVecOrMat, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64, rowsA::UnitRange{…}, colsA::UnitRange{…})
    @ Base ./arrayshow.jl:240
  [5] print_matrix(io::IOContext{…}, X::StructArrays.StructVector{…}, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64)
    @ Base ./arrayshow.jl:171
  [6] 
    @ Base ./arrayshow.jl:171 [inlined]
  [7] print_array
    @ ./arrayshow.jl:358 [inlined]
  [8] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, X::StructArrays.StructVector{@NamedTuple{…}, @NamedTuple{…}, Int64})
    @ Base ./arrayshow.jl:399
  [9] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:273
 [10] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [11] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:259
 [12] display
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:278 [inlined]
 [13] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [14] #invokelatest#2
    @ ./essentials.jl:887 [inlined]
 [15] invokelatest
    @ ./essentials.jl:884 [inlined]
 [16] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:315
 [17] (::REPL.var"#57#58"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:284
 [18] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [19] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:282
 [20] (::REPL.var"#do_respond#80"{…})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:911
 [21] #invokelatest#2
    @ Base ./essentials.jl:887 [inlined]
 [22] invokelatest
    @ Base ./essentials.jl:884 [inlined]
 [23] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2656
 [24] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1312
 [25] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/REPL/src/REPL.jl:386
Some type information was truncated. Use `show(err)` to see complete types.

```

### PR DESCRIPTION
**Pull request by Moelf**
fix #321

### CODE REVIEW

**Comment by peremato** [comment]
Thanks @Moelf.  I works nicely!

**Comment by peremato** [comment]
Would it be possible to make a new release  such that I can release what I have which depends on UnROOT?

**Comment by Moelf** [comment]
@peremato feel free to do it if you have time. I personally would try to understand if using Index64 is bad to begin with or what... but we can always fix bugs later

**Comment by Moelf** [comment]
ok merging this because `typemax(Int64)` bits is more than 1 EB

**Pull request merged**
