### PR TITLE
TVectorT<double> support

### PR DESCRIPTION
**Pull request by tamasgal**
This is a preliminary support for `TVectorT<double>` stuff sitting directly on the tree. We happen to have a couple of them produced by a specific simulation application.

Note that this PR is a temporary fix, I am working on a general solution to parse this such stuff.

### CODE REVIEW

**Comment by tamasgal** [comment]
I need a test file...

If anyone could help out with a ROOT file containing a single `TVectorT<double>` entry in the main tree, I'd highly appreciate it 😉

**Comment by Moelf** [comment]
Can we not make one ourselves?

**Comment by tamasgal** [comment]
Yes that was the request 😅 I am now on the bike

**Comment by tamasgal** [comment]
So far I don't understand how to attach a single object (like a `TVectorT<double>`) to the `TTree`, but reading branches with `TVectorT<...>` is also needed, so I need to consolidate the parsing anyways.

For the sake of completeness, here is what I quickly tried (but it creates a branch, obviously):

```
root [0] TFile rootfile("test.root", "RECREATE");
root [1] TTree *t = new TTree("t", "Some TVector data");
root [2] TVectorT<
tab completion not implemented for this context
root [2] TVectorT<double> data(3);
root [3] data
(TVectorT<double> &) Name: TVectorT<double> Title:
root [4] data[0]
(double) 0.0000000
root [5] data[0] = 1.1;
root [6] data[1] = 2.2;
root [7] data[2] = 3.3;
root [8] data[3] = 4.3;
Error in <TVectorT<double>::operator()>: Request index(3) outside vector range of 0 - 3
root [9] data
(TVectorT<double> &) Name: TVectorT<double> Title:
root [10] t->Branch("test", &data);
root [11] rootfile.Write();
root [12] rootfile.Close();
```

I'll continue tomorrow.

**Comment by tamasgal** [comment]
Ah, just realised, the object is not in the tree, it's right at the top level.

**Comment by tamasgal** [comment]
ChatGPT for the rescue 🙈 -- I needed to ask for a few iterations but it was ok ;)

```
TFile* file = new TFile("example.root", "RECREATE");
TVectorT<double>* vec = new TVectorT<double>(3);
(*vec)[0] = 1.1;
(*vec)[1] = 2.2;
(*vec)[2] = 3.3;

TDirectory* dir = file->GetDirectory("/");
dir->WriteObject(vec, "vector_double");
file->Close();
```

and voila

```julia
julia> using UnROOT

julia> f = ROOTFile("example.root")
ROOTFile with 1 entry and 1 streamer.
example.root
└─ vector_double (TVectorT<double>)


julia> f["vector_double"]
3-element Vector{Float64}:
 1.1
 2.2
 3.3
```

**Pull request merged**
