### PR TITLE
[WIP] resurrecting in place `ntoh`

### PR DESCRIPTION
**Pull request by aminnj**
Resurrection of https://github.com/tamasgal/UnROOT.jl/pull/101 (which means some copy-pasting from @Moelf ;) ). Basically, we add a `inplace::Bool` to `interped_data` which toggles between doing `ntoh.(reinterpret(...))` (copy) or an inplace-variant, both returning the same type which means it's still type stable.

But with a small modification, `basketarray()`'s return type depends on the boolean. Probably this can be fixed with a barrier function to discard  the `Ref{UInt8[]}` if called with `inplace=false` (the default.

Unit tests all pass.

```julia
julia> using UnROOT

julia> const t = LazyTree(ROOTFile("uncompressed_Run2012BC_DoubleMuParked_Muons.root"),"Events");

julia> function bar(t)
           for evt in t
               _ = evt.Muon_pt
           end
           nothing
       end
```

### before
```julia
julia> @btime sum(t.nMuon) seconds=10
  204.417 ms (6078 allocations: 469.98 MiB)
0x0000000008e67ad8

julia> @btime bar(t) seconds=10
  712.140 ms (14304 allocations: 1.82 GiB)
```

### after

```julia
julia> @btime sum(t.nMuon) seconds=10
  205.316 ms (6780 allocations: 235.24 MiB)
0x0000000008e67ad8

julia> @btime bar(t) seconds=10
  725.626 ms (16241 allocations: 1.26 GiB)
```

Performance is pretty much the same but with less total allocated memory. If I profile `bar(t)` I see there's a materialization. I thought this should be in place??

image

### CODE REVIEW

**Comment by Moelf** [comment]
I know it probably doesn't get much better but this is very messy :(

**Comment by Moelf** [comment]
actually:
```julia
#before
(14304 allocations: 1.82 GiB)
#after
(16241 allocations: 1.26 GiB)
```

I think this means we shouldn't do this, the number of allocation increases probably caused slow down. And the difference isn't as big as the 2x in the `nMuon` case

**Comment by aminnj** [comment]
I agree it’s not pretty. I’ll keep this an open wip for now since at least it works. If we get inspiration for making it better and truly in place (?) that would be great :)

**Comment by tamasgal** [comment]
I also think that this needs a bit more time `;)` let's keep this floating around...

**Comment by Moelf** [comment]
I wonder if @oschulz has any opinion. In fact, it would be nice to have a variation of `VectorOfVector` that has a field for `Ref` to hold the original byte array...

**Comment by Moelf** [comment]
what happens if you make `Wrapper <:`

https://github.com/JuliaArrays/ArraysOfArrays.jl/blob/393a25de3796ae5dbf69760edcb659dc984ff0f5/src/array_of_similar_arrays.jl#L18

**Comment by oschulz** [comment]
I'm not sure I've understood all the implications here - are you looking for somethings like a `VectorOfVectors` wrapped around an [`UnsafeArray`](https://github.com/JuliaArrays/UnsafeArrays.jl)?

**Comment by Moelf** [comment]
the problem is we have an original byte array `A::Vector{UInt8}`, we want to wrap `VoV` around it except we want to "cast" it to, for example, `B::Vector{Int32}`, but if you cast it by `unsafe_wrap()`, GC thinks `A` is not needed and thus GC-ed and you get bad data in `VoV(B)`.

**Comment by oschulz** [comment]
But why can't we use `ReinterpretArray` if we have to keep the reference to `A` around anyway?

**Comment by Moelf** [comment]
because `ReinterpretArray` is slow for both:
1. `A .= ntoh.(A)`
2. everything user will later on do, such as looping over the branch

**Comment by oschulz** [comment]
> A .= ntoh.(A) (10x slower)

I wonder why ReinterpretArray is performing that much worse, compared to our custom wrappers. Well, probably can't be helped right now.

In that case I would recommend to use a `VectorOfVectors` around a custom wrapper - would that be workable? I don't think creating a special VoV type would increase performance, and it would generate more code to maintain long term.

**Comment by Moelf** [comment]
https://github.com/JuliaLang/julia/issues/42227#issuecomment-1037463738

on Julia master, `y .= ntoh.(y)` is no longer slow given `y` is an `ReinterpretedArray`

**Comment by aminnj** [comment]
It might be that zlib decompression + the calculation is washing out the true benchmark

**Pull request closed without merging**
