### PR TITLE
[WIP] add minimal RNTuple files to probe writing situation

### PR DESCRIPTION
**Pull request by Moelf**
here are two files written out each contain a single number (but different)

**DO NOT** conda root-nighly, it hasn't been building properly since 6.27 (Nov 2022)

I'm doing this for now:
```bash
$ source  /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-opt/setup.sh
$ root --version
ROOT Version: 6.31/01
Built for linuxx8664gcc on Nov 10 2023, 23:36:14
From heads/master@v6-31-01-251-gc5048fa
```
```julia
julia> ROOTFile("./test_ntuple_min1.root")["ntuple"]
UnROOT.RNTuple with 1 rows, 1 fields, and metadata:
  header:
    name: "ntuple"
    ntuple_description: ""
    writer_identifier: "ROOT v6.31/01"
    schema:
      RNTupleSchema with 1 top fields
      └─ :one_uint ⇒ Leaf{UInt32}(col=1)

  footer:
    cluster_summaries: UnROOT.ClusterSummary[ClusterSummary(num_first_entry=0, num_entries=1)]

julia> LazyTree("./test_ntuple_min1.root", "ntuple")
 Row │ one_uint
     │ UInt32
─────┼────────────
 1   │ 3435973836
```

cc. @tamasgal

### CODE REVIEW

**Comment by tamasgal** [comment]
Thanks!

**Comment by Moelf** [comment]
image

**Comment by Moelf** [comment]
I'm update the file to use https://root.cern/doc/v624/namespaceROOT_1_1Experimental.html#a27e0535a55521c5e8f050fc92840e110

setting the option to `kBare`:
image

**Comment by Moelf** [comment]
idk what they mean by think envelope, currently trying to reverse engineering from know header location:
```julia
julia> f = UnROOT.MmapStream("./test/samples/RNTuple/test_ntuple_min1.root");

julia> seek(f, 0x92)
UnROOT.MmapStream(UInt8[0x72, 0x6e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x00, 0x00, 0xf6  …  0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x1c, 0xe8, 0x9a, 0x3f], 146, 494)

julia> UnROOT._rntuple_read(f, UnROOT.RNTupleHeader)
UnROOT.RNTupleHeader(0x0000000000000000, 0x00000001, "ntuple", "", "ROOT v6.31/01", UnROOT.FieldRecord[parent=00, role=0, name=one_uint                      , type=std::uint32_t                                               repetition=0,], UnROOT.ColumnRecord[type=20, nbits=32, field_id=00, flags=0], UnROOT.AliasRecord[], UnROOT.ExtraTypeInfo[])
```

**Comment by Moelf** [comment]
```
E8 FF FF FF 01 00 00 00 10 00 00 00 14 00 20 00 00 00 00 00 00 00 00 00
```

is a useful pattern. This is what an empty `RNTupleListFrame` looks like

**Comment by Moelf** [comment]
via almost brute force, I also figured out where footer is:
```julia
julia> seek(f, 366)
UnROOT.MmapStream(UInt8[0x72, 0x6e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x00, 0x00, 0xf6  …  0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x1c, 0xe8, 0x9a, 0x3f], 366, 494)

julia> footer = UnROOT._rntuple_read(f, UnROOT.RNTupleFooter)
UnROOT.RNTupleFooter(0x0000000000000000, 0x47a1a5ae, UnROOT.RNTupleSchemaExtension(UnROOT.FieldRecord[], UnROOT.ColumnRecord[], UnROOT.AliasRecord[], UnROOT.ExtraTypeInfo[]), UnROOT.ColumnGroupRecord[], UnROOT.ClusterSummary[ClusterSummary(num_first_entry=0, num_entries=1)], UnROOT.ClusterGroupRecord[UnROOT.ClusterGroupRecord(0x00000001, UnROOT.EnvLink(0x0000003c, UnROOT.Locator(60, 0x000000000000012e)))], UnROOT.EnvLink[])

julia> position(f)
490
```

**Comment by Moelf** [comment]
looks like we won't have bare RNTuple in production :(

**Pull request closed without merging**
