### PR TITLE
Add vector<string> to the custom structures

### PR DESCRIPTION
**Pull request by 8me**
What the title says, nothing to fancy :wink:

### CODE REVIEW

**Comment by Moelf** [comment]
do you happen to have a test file for this

**Comment by 8me** [comment]
@tamasgal can you add some `usr` variables to `km3net_offline.root` test file, that you provide the perfect basis for some unittests :sweat_smile:

**Comment by tamasgal** [comment]
Touching existing test files is a no-no but we can use this one: https://git.km3net.de/km3py/km3net-testdata/-/blob/master/km3net_testdata/data/offline/usr-sample.root

**Comment by tamasgal** [comment]
Here is the reference test: https://git.km3net.de/km3py/km3io/-/blob/b71300ff1364394d01323a732585f0a8dae303b1/tests/test_offline.py#L539

**Comment by 8me** [comment]
@tamasgal ok will add the tests later

**Review by tamasgal — APPROVED** [review]

**Comment by tamasgal** [comment]
Thanks! Can you rebase onto master?

**Pull request merged**
